// // Get call to / implements the function
// app.get('/home', (req, res) => {
//     // res.send("Hey this is my first express response");
//     // res.sendFile(__dirname +  '/views/index.html');
//     // res.sendFile(path.join(__dirname, '/views/index.html'));
//     //Express renders template HTML generated by Ejs
//     const title = 'Chat Room';
//     const msgs = ['Hey', 'Hello, Whats up?'];
//     const viewData = {
//     	title: title,
//     	msgs: msgs
//     }
//     res.render('index', viewData); 
// });